# Kokoro TTS Self-Test Configuration - CPU Mode
# 默认配置文件（CPU 模式）

device: cpu
test_text: "Hello, this is a test of the Kokoro text-to-speech system. The system can convert text into natural-sounding speech."
voice: af_heart
lang_code: a
speed: 1.0
output_dir: /tmp/kokoro-selftest
model_path_env: KOKORO_LOCAL_MODEL_PATH

# Advanced options
max_chunk_size: 100
enable_verbose: false
