# Kokoro TTS Self-Test Configuration - GPU Mode
# GPU 加速配置文件

device: cuda
test_text: "GPU acceleration test for Kokoro TTS engine. This configuration uses CUDA for faster speech synthesis."
voice: af_heart
lang_code: a
speed: 1.0
output_dir: /tmp/kokoro-selftest
model_path_env: KOKORO_LOCAL_MODEL_PATH

# Advanced options
max_chunk_size: 100
enable_verbose: false
